# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

pod 'AFJSONRPCClient', '~> 2.1.1'
pod 'SDWebImage',              '3.7.1'
pod 'AFNetworking',            '2.5.1'
pod 'MBProgressHUD',           '0.9.1'
pod 'MBProgressHUDExtensions', '0.0.1'
pod 'pop',                     '1.0.7'
pod 'Masonry',                 '0.6.2'
